services:
  db:
    image: postgres:16
    ports:
      - "5432:5432"
    environment:
      POSTGRES_USER: echoic
      POSTGRES_PASSWORD: echoic
      POSTGRES_DB: echoic
    volumes:
      - postgres_data:/var/lib/postgresql/data

volumes:
  postgres_data:
