"""add_oral_attempts

Revision ID: 578f7075c285
Revises: a3f1b2c4d5e6
Create Date: 2026-04-17 21:07:38.272470

"""
from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

revision = '578f7075c285'
down_revision = 'a3f1b2c4d5e6'
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('oral_attempts',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('question_type', sa.String(), nullable=False),
    sa.Column('question_language', sa.String(), nullable=False),
    sa.Column('question_difficulty', sa.String(), nullable=True),
    sa.Column('question_prompt', sa.String(), nullable=False),
    sa.Column('question_reference', sa.String(), nullable=True),
    sa.Column('storage_backend', sa.String(), nullable=False),
    sa.Column('recording_path', sa.String(), nullable=False),
    sa.Column('accuracy_score', sa.Float(), nullable=True),
    sa.Column('fluency_score', sa.Float(), nullable=True),
    sa.Column('completeness_score', sa.Float(), nullable=True),
    sa.Column('word_scores', sa.JSON(), nullable=True),
    sa.Column('transcription', sa.String(), nullable=True),
    sa.Column('llm_score', sa.Float(), nullable=True),
    sa.Column('llm_feedback', sa.String(), nullable=True),
    sa.Column('llm_highlights', sa.JSON(), nullable=True),
    sa.Column('timer_secs', sa.Integer(), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.alter_column('collections', 'created_at',
               existing_type=postgresql.TIMESTAMP(),
               nullable=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('collections', 'created_at',
               existing_type=postgresql.TIMESTAMP(),
               nullable=True)
    op.drop_table('oral_attempts')
    # ### end Alembic commands ###
