"""add language to audio_files

Revision ID: 5cce4f7e6bb7
Revises: 169a9b672092
Create Date: 2026-04-08 20:44:24.267254

"""
from alembic import op
import sqlalchemy as sa


revision = '5cce4f7e6bb7'
down_revision = '169a9b672092'
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('audio_files', sa.Column('language', sa.String(), nullable=False, server_default='en'))
    op.alter_column('audio_files', 'language', server_default=None)
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('audio_files', 'language')
    # ### end Alembic commands ###
